protected/controllers/McController.php
<?php

class McController extends ControllerBase
{

    final public const TYPE_LINEUP = 0;
    final public const TYPE_RESULTS = 1;
    final public const TYPE_REPORT = 2;
    final public const TYPE_SLIDESHOW = 2;

    const CHECK_TYPE_IN_LINE = 'here';
    const CHECK_TYPE_ON_STAGE = 'called';

    private ?array $_events = null;

    private array $permission = [
        0 => 'mc_lineup',
        1 => 'mc_results',
        2 => 'mc_report',
        3 => 'mc_slideshow',
    ];

    private array $compStatus = [
        0 => 'e.mc = 1',
        1 => 'e.results = 1',
        2 => 'e.results = 1',
    ];


    /**
     * Note to self:
     * access controller does not validate user access to event
     **/

    public function _actionRules()
    {
        return [
            [
                'actions' => [
                    'lineup',
                    'lineupCallback',
                    'toggleStatus',
                    'entryInfo',
                    'image',
                    'competitions',
                ],
                'roles' => ['mc_lineup'],
            ],
            [
                'actions' => [
                    'results',
                    'presults',
                    'pcontestant',
                    'image',
                    'competitions',
                ],
                'roles' => ['mc_results'],
            ],
            [
                'actions' => [
                    'report',
                    'preport',
                    'pcontestant',
                    'image',
                    'competitions',
                ],
                'roles' => ['mc_results'],
            ],
            [
                'actions' => [
                    'slideshow',
                    'slideshowFields',
                    'image',
                    'competitions',
                ],
                'roles' => ['mc_slideshow'],
            ],
        ];

    }//end _actionRules()


    /**
     * Setup parent class
     *
     * @param CAction $action
     * @return bool
     */
    public function beforeAction($action)
    {
        $actionResult = parent::beforeAction($action);
        $this->breadcrumbs[] = [
            'label' => 'MC',
            'url' => Yii::app()->params['baseurl'] . '/mc/index',
        ];
        return $actionResult;

    }//end beforeAction()


    /*
        public function actionIndex() {
        $this->render('index');
        }
    */
    public function actionLineup()
    {
        $this->breadcrumbs[] = 'Lineup';

        Yii::app()->clientScript->registerScriptFile("/js/cj/mc.lineup.js", CClientScript::POS_HEAD);

        $this->render('lineup');

    }


    public function actionlineupCallback()
    {
        $this->layout = "//layouts/none";
        $comp = -1;
        if (isset($_GET['c'])) {
            $comp = (int)$_GET['c'];
        }

        $competition = null;
        $compObject = $this->validateCompetitionAccess($comp, self::TYPE_LINEUP);
        if ($compObject) {
            $cid = Yii::app()->params['clientid'];
            $competition = Competitions::model()->with("CEntries", "CEntries.Entry", "Event_mc")->findByAttributes(['id' => $comp, 'client' => $cid]);
            if (!$competition && !empty($comp) && $comp != -1) {
                Yii::app()->user->setFlash('error-mclineup', "Unable to find competition");
            }
        }
        $adata = [];
        foreach ($competition?->CEntries ?? [] as $entry) :
            $data = [];
            if (!$entry->active && !(isset($_GET['w']) && $_GET['w'] == 'true')) {
                continue;
            }

            $data[] = $entry->id;
            $options = [
                'competition' => $entry->competition,
                'entry' => $entry->entry,
                'id' => $entry->id,
                'disabled' => !$entry->active,
            ];
            $data[] = $this->renderPartial('//mc/namelink', $options + ['name' => $entry->Entry->name], TRUE);
            $data[] = $this->renderPartial('//mc/checkbox', $options + ['fieldId' => 'heredcb', 'label' => 'In Line', 'checked' => $entry->here], TRUE);
            $data[] = $this->renderPartial('//mc/checkbox', $options + ['fieldId' => 'calledcb', 'label' => 'Called', 'checked' => $entry->called], TRUE);

            $adata[] = $data;
        endforeach;

        echo json_encode(['data' => $adata], JSON_THROW_ON_ERROR);
        die();

    }

    public function actionSlideshow()
    {
        $this->breadcrumbs[] = 'Slideshow';
        Yii::app()->clientScript->registerScriptFile("/js/theme/colorbox/jquery.colorbox-min.js", CClientScript::POS_HEAD);
        Yii::app()->clientScript->registerCssFile('/js/theme/colorbox/colorbox.css');
        Yii::app()->clientScript->registerScriptFile("/js/cj/mc.slideshow.js", CClientScript::POS_HEAD);

        $this->render('slideshow');

    }//end actionSlideshow()


    public function actionSlideshowFields()
    {

        if (isset($_GET['c'])) {
            $comp = (int)$_GET['c'];
        } else {
            $comp = -1;
        }

        $compObject = $this->validateCompetitionAccess($c, self::TYPE_SLIDESHOW);
        if (!$compObject) {
            throw new CHttpException(403, 'You do not have access to that.');
        }

        $fieldData = [];
        /*
         * field id -> images/name -> entry id ->image/competitions[]/name
         */
        $cid = Yii::app()->params['clientid'];

        if ($comp == -2) {
            $competitions = Competitions::model()->with("CEntries", "CEntries.Entry", "CEntries.Entry.Fields", "Event_mc", "Fields_mc")->findAllByAttributes(['client' => $cid]);
        } else {
            $competitions = [];
            $competitions[] = Competitions::model()->with("CEntries", "CEntries.Entry", "CEntries.Entry.Fields", "Event_mc", "Fields_mc")->findByAttributes(['id' => $comp, 'client' => $cid]);
        }

        foreach ($competitions as $competition) {
            foreach ($competition->Fields_mc as $field) {
                // loop through fields
                if ($field->Field->Type->validator == 'uimage') {
                    // if it is an image
                    if (empty($fieldData[$field->field])) {
                        // and it doesn't exist yet
                        $fieldData[$field->field] = [
                            // create it
                            'name' => $field->Field->name,
                            'images' => [],
                        ];
                    }

                    // add contestants to field
                    foreach ($competition->CEntries as $e) {
                        if ($e->here != 1) {
                            continue;
                        }

                        $e = $e->Entry;
                        foreach ($e->Fields as $cfield) {
                            if ($cfield->field == $field->field) {
                                if (empty($cfield->value)) {
                                    continue;
                                }

                                if (empty($fieldData[$field->field]['images'][$e->id])) {
                                    // add competitions to field
                                    $fieldData[$field->field]['images'][$e->id] = [
                                        'image' => $cfield->value,
                                        'competitions' => [],
                                        'name' => $e->name,
                                    ];
                                }

                                $fieldData[$field->field]['images'][$e->id]['competitions'][] = __EF($competition->name);
                            }
                        }
                    }//end foreach
                }//end if
            }//end foreach
        }//end foreach

        echo $this->renderPartial('pslideshowfields', ["fieldData" => $fieldData]);
        die();

    }//end actionSlideshowFields()


    private function translateType($type)
    {
        $type = match ($type) {
            'results' => self::TYPE_RESULTS,
            'report' => self::TYPE_REPORT,
            default => self::TYPE_LINEUP,
        };

        return $type;

    }//end translateType()


    public function actionCompetitions()
    {
        $this->layout = "//layouts/none";
        $result = [
            'success' => true,
            'competitions' => [],
        ];
        $type = $this->translateType($_GET['type']);

        foreach ($this->getEventList($type) as $eid => $comps) {
            foreach ($comps['competitions'] as $c => $data) {
                $result['competitions'][] = [
                    'name' => $data['name'] . " (" . $data['count'] . ")",
                    'id' => $c,
                ];
            }
        }

        echo json_encode($result, JSON_THROW_ON_ERROR);
        die();

    }//end actionCompetitions()


    // TODO: better security
    public function actionImage()
    {
        $i = $_GET['i'];
        str_replace('.png', '', (string)$i);
        if (!isset($i)) {
            return;
        }

        $command = Yii::app()->db->createCommand('SELECT * from uploads where client=:client and id=:id ');

        $client = Yii::app()->params['clientid'];
        $command->bindParam(":client", $client, PDO::PARAM_INT);
        $command->bindParam(":id", $i, PDO::PARAM_INT);
        $row = $command->queryRow();
        if ($row) {
            $f = $row['file'];
            header('Cache-control: max-age=' . (60 * 60 * 24));
            header('Expires: ' . gmdate(DATE_RFC1123, (time() + 60 * 60 * 24)));
            if (str_ends_with((string)$f, 'jpg')) {
                header('Content-Type: image/jpeg');
                echo file_get_contents($f);
            } else if (str_ends_with((string)$f, 'png')) {
                header('Content-Type: image/png');
                echo file_get_contents($f);
            }
        }

    }//end actionImage()

protected/views/generate/breadcrumbs.php
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <?php foreach ($this->breadcrumbs as $index => $breacrumb) : ?>
            <li class="breadcrumb-item <?php echo $index == (sizeof($this->breadcrumbs) - 1) ? "active" : "" ?>">
                <?php if (is_array($breacrumb)) : ?>
                    <a href="<?php echo $breacrumb['url'] ?? '#'; ?>">
                        <?php echo $breacrumb['label'] ?? ''; ?>
                    </a>
                <?php else : ?>
                    <span><?php echo $breacrumb ?></span>
                <?php endif; ?>
            </li>

        <?php endforeach; ?>
    </ol>
</nav>

protected/views/generate/competitionDD.php
<select id="<?php echo $id ?>" class="form-select">
<!--    <option value="-1"></option>-->
    <?php
    foreach ($events as $eid => $e) :
        ?>
        <optgroup label="<?php echo __EF($e['name']) ?>">
        <?php foreach ($e['competitions'] as $id => $c) : ?>
        <option value="<?php echo $id ?>"><?php echo __E($c['name']) ?> (<?php echo $c['count']?>)</option>
        <?php endforeach; ?>
        </optgroup><?php
    endforeach;
    ?>
</select>

protected/views/generate/listSelector.php
<?php

        ;
        Yii::app()->clientScript->registerScriptFile('/js/listSelector.js');
        Yii::app()->clientScript->registerCssFile('/css/listSelector.css');

        $safeName = str_replace(["[", "]"], "_", (string) $inputName);
if (str_ends_with($safeName, "_")) {
    $safeName = substr($safeName, 0, (strlen($safeName) - 1));
}

?>
<table class="listselector dataTable <?php echo (intval($usecheckboxes) + 2)?>-col">
       <thead><tr><th>&nbsp;</th><th><?php echo $title?></th><?php if ($usecheckboxes) :
            ?><th><?php echo $checkboxtitle?></th><?php
      endif; ?></tr></thead>
        <tbody>
            <?php foreach ($items as $k => $v) :
                $a = '';
                if (is_array($v)) {
                    $tooltip = "title='".__E(__E($v['tooltip']))."' class='tooltip'";
                    $a       = $v['attributes'];
                    $v       = $v['value'];
                }
                ?>
                    <tr>
                        <td><input type="checkbox" name="<?php echo $inputName?>[]" <?php echo $a?> value="<?php echo $k?>" <?php echo (is_array($selected)&&array_key_exists($k, $selected) ? "checked" : "")?>  /></td>
                        <td><?php echo __E($v)?></td>
                        <?php if ($usecheckboxes) : ?>
                        <td><input type="checkbox" class="iphone" name="<?php echo $inputName."[{$checkboxname}][]"?> value="<?php echo $k?>" <?php echo (is_array($checked)&&in_array($k, $checked) ? "checked" : "")?> /></td>
                        <?php endif; ?>
                   </tr>
            <?php endforeach; ?>    
            
        </tbody>
 </table>

protected/views/generate/menu.php
<?php
$b = Yii::app()->params['baseurl'];

$m = [
    // array('label'=>'Home', 'url'=>$b,'icon'=>'/css/'.VERSION.'/assets/icons/small_icons_2/settings.png'),
    [
        'label' => 'Admin',
        'access' => 'admin',
        'icon' => 'fa-gear',
        'url' => '#',
        'activeCheck' => $b . '/settings/',
        // check this url
        'children' => [
            [
                'label' => 'Configuration',
                'access' => 'admin/settings',
                'icon' => '',
                'url' => $b . '/settings/configure',
                'active' => true,
            ],
            [
                'label' => 'Events',
                'access' => 'admin/events',
                'icon' => '',
                'url' => $b . '/settings/events',
                'active' => true,
            ],
            [
                'label' => 'Competitions',
                'access' => 'admin/competitions',
                'icon' => '',
                'url' => $b . '/settings/competitions',
                'active' => true,
            ],
            [
                'label' => 'Statistics',
                'access' => 'admin/competitions',
                'icon' => '',
                'url' => $b . '/settings/statistics',
                'active' => true,
            ],
        ],
    ],
    [
        'label' => 'MC',
        'access' => [
            'mc_lineup',
            'mc_results',
            'mc_report',
        ],
        'icon' => 'fa-microphone',
        'url' => '#',
        'activeCheck' => $b . '/mc/',
        'children' => [
            [
                'label' => 'Lineup',
                'access' => 'mc_lineup',
                'icon' => 'fa-bars',
                'url' => $b . '/mc/lineup',
                'active' => false,
            ],
            [
                'label' => 'Slideshow',
                'access' => 'mc_slideshow',
                'icon' => 'fa-desktop',
                'url' => $b . '/mc/slideshow',
                'active' => false,
            ],
            [
                'label' => 'Results',
                'access' => 'mc_results',
                'icon' => 'fa-sort-amount-desc',
                'url' => $b . '/mc/results',
                'active' => false,
            ],
            [
                'label' => 'Report',
                'access' => 'mc_report',
                'icon' => 'fa-building fa-rotate-180',
                'url' => $b . '/mc/report',
                'active' => false,
            ],
        ],
    ],
    [
        'label' => 'Registration',
        'access' => 'registration',
        'icon' => 'fa-id-card',
        'url' => $b . '/register',
        'activeCheck' => $b . '/register',
    ],
    // array('label' => 'Register', 'url' => $b . '/register/', 'visible' => Yii::app()->user->checkAccess('register'), 'icon' => '/css/assets/icons/small_icons/People.png'),
    [
        'label' => 'Judge',
        'access' => 'judge',
        'icon' => 'fa-balance-scale',
        'url' => $b . '/judge',
        'activeCheck' => $b . '/judge',
    ],

];

$generateMenu = function ($menu_items) use (&$generateMenu) {
    foreach ($menu_items as $index => $menu_item) {
        $activeC = !empty($menu_item['activeCheck']) ? $menu_item['activeCheck'] : $menu_item['url'];
        $active = str_contains((string)Yii::app()->request->requestUri, (string)$activeC) ? 'active open' : '';
        $children = $menu_item['children'] ?? [];

        if ($menu_item['access'] == '' || Yii::app()->user->hasRole($menu_item['access'])) :
            ?>
            <li class="<?php echo $active ?>">
                <?php if (!empty($children)) : ?>
                <a href="#"
                   class="d-flex dropdown-toggle text-light border-0 bg-transparent align-items-center justify-content-start"
                   data-bs-toggle="collapse"
                   data-bs-target="#submenu-<?php echo $index ?>"
                   aria-controls="sidebar-nav" aria-expanded="false" aria-label="Expand navigation">
                    <?php else : ?>
                    <a href="<?php echo $menu_item['url'] ?>"
                       class="d-flex align-items-center justify-content-start <?php echo $active ?>">
                        <?php endif; ?>
                        <?php echo !empty($menu_item['icon']) ? "<i class=\"fa ${menu_item['icon']}\"></i>" : '' ?>
                        <span class="px-3"><?php echo $menu_item['label'] ?></span>
                    </a>
                    <?php if (!empty($children)) {
                        echo '<ul class="submenu collapse ' . ($active ? 'show' : '') . '" id="submenu-' . $index . '">';
                        $generateMenu($menu_item['children']);
                        echo '</ul>';
                    }
                    ?>
            </li>
        <?php endif;
    }//end foreach

};

?>
<?php if (!empty($logo)) : ?>
    <div class="logo-container mt-3">
        <a href="<?php echo Yii::app()->params['baseurl'] ?>">
            <img src="<?php echo $logo ?>" alt=""/>
            <span class="visually-hidden">
            <?php echo __E(Yii::app()->config->get('name')); ?>
            </span>
        </a>
    </div>
<?php else: ?>
    <div class="logo-container mt-3 h2 text-center">
        <a href="<?php echo Yii::app()->params['baseurl'] ?>">
            <span class="">
            <?php echo __E(Yii::app()->config->get('name')); ?>
            </span>
        </a>
    </div>
<?php endif; ?>
    <div class="">
        <ul class="nav nav-pills flex-column p-0 mt-3 vw-50">
            <?php echo $generateMenu($m); ?>
        </ul>

    </div>
<?php

protected/views/generate/messages.php
<?php

$messages = Yii::app()->user->getFlashes();

if(empty($messages)){
    return;
}
?>
<div class="main-box-body clearfix">
<?php

foreach($messages as $type => $message):

    if (preg_match('/^danger/', $type)){
        $alertType = 'alert-danger';
        $icon = 'circle-error';
    } elseif (preg_match('/^success/', $type)){
        $alertType = 'alert-success';
        $icon = 'circle-check';
    } elseif (preg_match('/^warning/', $type)){
        $alertType = 'alert-warning';
        $icon = 'circle-warning';
    } else {
        $alertType = 'alert-info';
        $icon = 'circle-info';
    }

    ?>
    <div class="alert <?= $alertType ?> alert-dismissible fade show" role="alert">
        <?php
        echo $message; // Message should be escaped already?
        ?>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

<?php endforeach;

protected/views/generate/notification.php
                    <div class="notification <?php echo $notification?>"> 
                        <span></span> 
                        <div class="text"> 
                            <p><strong><?php echo $head?></strong> <?php echo $message?></p> 
                        </div> 
                    </div> 